### ISSUE TITLE
BoxShadow Tracking Ticket

### ISSUE THREAD

**Issue by maltenuhn** [concrete-utopia/utopia#1026]
**Issues from Usage**

- [ ] BoxShadow inspector control doesn't work with three-value syntax
- [ ] Control shows HSV color syntax, but saves RGBA syntax
- [ ] BoxShadow can't be removed by dragging it far enough away
- [ ] Adding a shadow should focus the first input field so you can tab through
- [ ] There is no control remove all box shadows except for the (invisible) context menu
- [ ] No support for `inset` syntax
- [ ] Right-clicking on a row seems to pass through the click to its parent, and _also_ opens a context menu on the parent

![image](https://user-images.githubusercontent.com/2945037/113061600-384d7400-91aa-11eb-9dc5-c07bdc473723.png)
